apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-test
  labels:
    app: account
spec:
  selector:
    matchLabels:
      app: account
      tier: test
  template:
    metadata:
      labels:
        app: account
        tier: test
    spec:
      containers:
      - image: hatena-intern-2020-account-test
        imagePullPolicy: Never
        name: account-test
        command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
        envFrom:
        - configMapRef:
            name: account-test-env-vars
