apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app.yaml
- db.yaml
- test.yaml
secretGenerator:
- name: blog-app-secret
  files:
  - secret/account-ecdsa-public.pem
configMapGenerator:
- name: blog-app-env-vars
  literals:
  - MODE=development
  - DATABASE_DSN=root@(blog-db:3306)/intern_2020_blog?time_zone=UTC&parseTime=true&loc=UTC
  - ACCOUNT_ADDR=account:50051
  - RENDERER_ADDR=renderer-go:50051
- name: blog-test-env-vars
  literals:
  - TEST_DATABASE_DSN=root@(blog-db:3306)/intern_2020_blog_test?time_zone=UTC&parseTime=true&loc=UTC
- name: blog-db-schema-config
  files:
  - config/schema.sql
